[[tables]]
  Name = "userprofile"

  [[tables.Cols]]
    TableName = "userprofile"
    Name = "first_name"
    Type = "character varying"

  [[tables.Cols]]
    TableName = "userprofile"
    Name = "email"
    Type = "character varying"

  [[tables.Cols]]
    TableName = "userprofile"
    Name = "last_name"
    Type = "character varying"
